### ISSUE TITLE
Release a new version with Array fixes

### ISSUE THREAD

**Issue by evaryont** [jcamenisch/ENV_BANG#13]
Friendly reminder. :smile_cat: 

I'm getting bit by https://github.com/jcamenisch/ENV_BANG/pull/9, would be nice to have a version released onto rubygems that includes the fix.

**Comment by jcamenisch** [comment]
Doh! Good point. Thanks for the ping.

**Comment by jcamenisch** [comment]
OK, @evaryont, version bumped to 0.2.10, and pushed to rubygems.org.
