### ISSUE TITLE
Could use another maintainer (or two?)

### ISSUE THREAD

**Issue by jcamenisch** [jcamenisch/ENV_BANG#16]
I've moved to an environment where we don't use ENV_BANG, and I'm not sure we ever will given the direction we're headed. That means I'm a pretty lousy maintainer of this project.

Does anyone want to help shepherd this library for a while? I don't think it needs to get more complex than it is, but any remaining glitches or corner cases can hopefully be handled by someone who's using it day in and day out. It could potentially use improvements too—not toward greater complexity, but perhaps toward better polish.

@nbibler, you've been the most attentive user to the details, but I know you're a busy guy. Do you expect to be using ENV_BANG into the future?

**Comment by nbibler** [comment]
Hah. Yeah.... I'm supposed to be helping to maintain vcr but failing pretty miserably at that, already. :(  I'm happy to help when I can, but I can't really commit to anything more at the moment.
