### ISSUE TITLE
Does ENV! also include per-environment config files like dotenv

### ISSUE THREAD

**Issue by deiga** [jcamenisch/ENV_BANG#7]
Let's say I have an `.env` and `.env.test`, does `ENV!` automatically include both, when I run `RAILS_ENV=test` commands?

**Comment by mildred** [comment]
For everyone interested, dotenv works well with envbang. With Rails, you just needs to put envbang after dotenv in your Gemfile so the environment is populated before ENV! looks at it. If you manually initialize them, make sure dotenv is initialized before ENV!.

**Comment by jcamenisch** [comment]
Thank you, @mildred. I'm glad to hear this is working well for you!
